// SPDX-FileCopyrightText: 2026 Polaris Contributors
// SPDX-License-Identifier: GPL-3.0-only

package com.slte.app.ui.theme

import androidx.compose.ui.graphics.Color

// Aurora Polaris 亮色配色：bg-0 #F5F6F8 / surface #FFFFFF / cyan #0284C7 / gold #B45309
val md_light_primary = Color(0xFF0284C7)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFF5F7FA)
val md_light_onPrimaryContainer = Color(0xFF0A3058)
val md_light_secondary = Color(0xFF64748B)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFE5EAF1)
val md_light_onSecondaryContainer = Color(0xFF475569)
val md_light_tertiary = Color(0xFF6D28D9)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFEDE7FB)
val md_light_onTertiaryContainer = Color(0xFF2E1065)
val md_light_error = Color(0xFFDC2626)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFFCE8E8)
val md_light_onErrorContainer = Color(0xFF8B1A1A)
val md_light_background = Color(0xFFF5F6F8)
val md_light_onBackground = Color(0xFF0F172A)
val md_light_surface = Color(0xFFFFFFFF)
val md_light_onSurface = Color(0xFF0F172A)
val md_light_surfaceVariant = Color(0xFFF5F7FA)
val md_light_onSurfaceVariant = Color(0xFF475569)
val md_light_outline = Color(0xFFE2E8F0)
val md_light_outlineVariant = Color(0xFFE5EAF1)

// Aurora Polaris 暗色配色：bg-0 #070B16 / surface #182241 / cyan #5DD4F5 / gold #FFC857
val md_dark_primary = Color(0xFF5DD4F5)
val md_dark_onPrimary = Color(0xFF0A1B2E)
val md_dark_primaryContainer = Color(0xFF1E2A4D)
val md_dark_onPrimaryContainer = Color(0xFFB8C4DC)
val md_dark_secondary = Color(0xFF6B7B99)
val md_dark_onSecondary = Color(0xFFF8FAFC)
val md_dark_secondaryContainer = Color(0xFF243156)
val md_dark_onSecondaryContainer = Color(0xFFB8C4DC)
val md_dark_tertiary = Color(0xFFC084FC)
val md_dark_onTertiary = Color(0xFF0A1B2E)
val md_dark_tertiaryContainer = Color(0xFF2A1F3D)
val md_dark_onTertiaryContainer = Color(0xFFB8C4DC)
val md_dark_error = Color(0xFFF87171)
val md_dark_onError = Color(0xFF0A1B2E)
val md_dark_errorContainer = Color(0xFF3A1A1A)
val md_dark_onErrorContainer = Color(0xFFF87171)
val md_dark_background = Color(0xFF070B16)
val md_dark_onBackground = Color(0xFFF8FAFC)
val md_dark_surface = Color(0xFF182241)
val md_dark_onSurface = Color(0xFFF8FAFC)
val md_dark_surfaceVariant = Color(0xFF1E2A4D)
val md_dark_onSurfaceVariant = Color(0xFFB8C4DC)
val md_dark_outline = Color(0xFF2A3550)
val md_dark_outlineVariant = Color(0xFF243156)
